### ISSUE TITLE
lab3 kvraft tests

### ISSUE THREAD

**Issue by overvenus** [overvenus/labs6824#14]
To complete the lab3 kvraft, we needs to port tests too. Here it the TODO list:

- [x] TestBasic3A #12
- [x] TestConcurrent3A #12
- [x] TestUnreliable3A #12
- [x] TestUnreliableOneKey3A #17 
- [x] TestOnePartition3A #17 
- [x] TestManyPartitionsOneClient3A #12
- [x] TestManyPartitionsManyClients3A #12
- [x] TestPersistOneClient3A #12
- [x] TestPersistConcurrent3A #12
- [x] TestPersistConcurrentUnreliable3A #12
- [x] TestPersistPartition3A #12
- [x] TestPersistPartitionUnreliable3A #12
- [x] TestPersistPartitionUnreliableLinearizable3A
- [x] TestSnapshotRPC3B #18
- [x] TestSnapshotSize3B #18
- [x] TestSnapshotRecover3B #12
- [x] TestSnapshotRecoverManyClients3B #12
- [x] TestSnapshotUnreliable3B #12
- [x] TestSnapshotUnreliableRecover3B #12
- [x] TestSnapshotUnreliableRecoverConcurrentPartition3B #12
- [x] TestSnapshotUnreliableRecoverConcurrentPartitionLinearizable3B

**Comment by Connor1996** [comment]
> To complete the lab3 kvraft, we needs to port tests too. Here it the TODO list:
> 
> * [x]  TestBasic3A #12
> * [x]  TestConcurrent3A #12
> * [x]  TestUnreliable3A #12
> * [x]  TestUnreliableOneKey3A #17
> * [x]  TestOnePartition3A #17
> * [x]  TestManyPartitionsOneClient3A #12
> * [x]  TestManyPartitionsManyClients3A #12
> * [x]  TestPersistOneClient3A #12
> * [x]  TestPersistConcurrent3A #12
> * [x]  TestPersistConcurrentUnreliable3A #12
> * [x]  TestPersistPartition3A #12
> * [x]  TestPersistPartitionUnreliable3A #12
> * [x]  TestPersistPartitionUnreliableLinearizable3A #16
> * [x]  TestSnapshotRPC3B #18
> * [x]  TestSnapshotSize3B #18
> * [x]  TestSnapshotRecover3B #12
> * [x]  TestSnapshotRecoverManyClients3B #12
> * [x]  TestSnapshotUnreliable3B #12
> * [x]  TestSnapshotUnreliableRecover3B #12
> * [x]  TestSnapshotUnreliableRecoverConcurrentPartition3B #12
> * [x]  TestSnapshotUnreliableRecoverConcurrentPartitionLinearizable3B #16
