### ISSUE TITLE
lab2 raft tests

### ISSUE THREAD

**Issue by overvenus** [overvenus/labs6824#6]
To complete the lab2 raft, we needs to port tests too. Here it the TODO list:

- [x] TestInitialElection2A #5
- [x] TestReElection2A
- [x] TestBasicAgree2B
- [x] TestFailAgree2B
- [x] TestFailNoAgree2B
- [x] TestConcurrentStarts2B
- [x] TestRejoin2B
- [x] TestBackup2B
- [x] TestCount2B
- [x] TestPersist12C
- [x] TestPersist22C
- [x] TestPersist32C
- [x] TestFigure82C
- [x] TestUnreliableAgree2C
- [x] TestFigure8Unreliable2C
- [x] TestReliableChurn2C
- [x] TestUnreliableChurn2C

**Comment by nolouch** [comment]
* [ ]  TestReElection2A @nolouch
* [ ]  TestBasicAgree2B @nolouch
